// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euzgkhndlcrugspzuldm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1emdraG5kbGNydWdzcHp1bGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczODI5MjQsImV4cCI6MjA1Mjk1ODkyNH0.yPJXl7C4ER359ZoPrT21hl2C0Fdjwv7wv3jTZkgsdgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);